"""initial schema

Revision ID: b626b1bdcf13
Revises: 
Create Date: 2026-09-03 12:30:38.851644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b626b1bdcf13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('birth_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ho_ten', sa.String(length=255), nullable=True),
    sa.Column('ngay_sinh_duong', sa.Date(), nullable=False),
    sa.Column('gio_sinh', sa.Integer(), nullable=False),
    sa.Column('phut_sinh', sa.Integer(), nullable=False),
    sa.Column('gioi_tinh', sa.Enum('nam', 'nu', name='gioi_tinh_enum'), nullable=False),
    sa.Column('ngay_sinh_am', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('birth_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_birth_profiles_user_id'), ['user_id'], unique=False)

    op.create_table('chat_histories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('he_thong', sa.Enum('tu_vi', 'kinh_dich', 'bat_tu', 'nhan_tuong', name='he_thong_enum'), nullable=False),
    sa.Column('reference_id', sa.Uuid(), nullable=True),
    sa.Column('cau_hoi', sa.Text(), nullable=False),
    sa.Column('tra_loi', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_histories_he_thong'), ['he_thong'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_histories_reference_id'), ['reference_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_histories_user_id'), ['user_id'], unique=False)

    op.create_table('que_kinh_dich_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cau_hoi', sa.Text(), nullable=True),
    sa.Column('ma_que_chinh', sa.String(length=50), nullable=False),
    sa.Column('ma_que_bien', sa.String(length=50), nullable=True),
    sa.Column('hao_dong', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('que_kinh_dich_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_que_kinh_dich_results_user_id'), ['user_id'], unique=False)

    op.create_table('tuong_anh_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('loai_anh', sa.Enum('tay', 'mat', name='loai_anh_enum'), nullable=False),
    sa.Column('duong_dan_anh', sa.String(length=500), nullable=False),
    sa.Column('dac_diem_quan_sat_json', sa.JSON(), nullable=True),
    sa.Column('da_duoc_xoa', sa.Boolean(), nullable=False),
    sa.Column('ngay_het_han_luu_tru', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tuong_anh_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tuong_anh_results_user_id'), ['user_id'], unique=False)

    op.create_table('usage_quotas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('ngay', sa.Date(), nullable=False),
    sa.Column('so_luot_da_dung', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'ngay', name='uq_user_daily_quota')
    )
    with op.batch_alter_table('usage_quotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_quotas_ngay'), ['ngay'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_quotas_user_id'), ['user_id'], unique=False)

    op.create_table('la_so_tu_vi_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('birth_profile_id', sa.Uuid(), nullable=False),
    sa.Column('du_lieu_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['birth_profile_id'], ['birth_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('la_so_tu_vi_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_la_so_tu_vi_results_birth_profile_id'), ['birth_profile_id'], unique=True)

    op.create_table('tu_tru_results',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('birth_profile_id', sa.Uuid(), nullable=False),
    sa.Column('du_lieu_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['birth_profile_id'], ['birth_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tu_tru_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tu_tru_results_birth_profile_id'), ['birth_profile_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tu_tru_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tu_tru_results_birth_profile_id'))

    op.drop_table('tu_tru_results')
    with op.batch_alter_table('la_so_tu_vi_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_la_so_tu_vi_results_birth_profile_id'))

    op.drop_table('la_so_tu_vi_results')
    with op.batch_alter_table('usage_quotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_quotas_user_id'))
        batch_op.drop_index(batch_op.f('ix_usage_quotas_ngay'))

    op.drop_table('usage_quotas')
    with op.batch_alter_table('tuong_anh_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tuong_anh_results_user_id'))

    op.drop_table('tuong_anh_results')
    with op.batch_alter_table('que_kinh_dich_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_que_kinh_dich_results_user_id'))

    op.drop_table('que_kinh_dich_results')
    with op.batch_alter_table('chat_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_histories_user_id'))
        batch_op.drop_index(batch_op.f('ix_chat_histories_reference_id'))
        batch_op.drop_index(batch_op.f('ix_chat_histories_he_thong'))

    op.drop_table('chat_histories')
    with op.batch_alter_table('birth_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_birth_profiles_user_id'))

    op.drop_table('birth_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
